feat: cargo workspace configuration and bazel build files for hermetic environment (#257)
RATIONALE:

Since we're supporting multiple languages in the repo, over time the
test running time and managing the environment to ensure we get hermetic
builds will become complicated. As a result, it is prudent to use a
proper build system to build and run tests orders of magnitude faster.

CHANGELOG:
- [ ] Add build files for go, ts.
- [ ] Add stub smoke tests for cargo workspace and java.
- [ ] Update setup script to install bazelisk.
- [ ] Add bazel configuration.
- [ ] Update hooks to run these tests.

diff --git a/scripts/fmt b/scripts/fmt
--- a/scripts/fmt
+++ b/scripts/fmt
@@ -59,9 +59,16 @@ fi
 popd
 
 # Format all rust code
-pushd "${TOP_DIR}/python/handlebarrz"
+pushd "${TOP_DIR}"
 cargo fmt --all
 if [[ $? -ne 0 ]]; then
   exit 1
 fi
 popd
+
+# Format all build files.
+if ! command -v "buildifier" >/dev/null 2>&1; then
+  echo "Buildifier not found. Installing via go install..."
+  go install github.com/bazelbuild/buildtools/buildifier@latest
+fi
+buildifier -r "${TOP_DIR}"
