feat: script to update all deps in one go and update deps (#130)
CHANGELOG:
- [ ] Add `scripts/update_deps` to update all dependencies.
- [ ] Add running rust tests to `scripts/run_tests`
- [ ] Update JS test thresholds.
- [ ] Fix an unbound variable issue in `scripts/run_rust_tests`

diff --git a/scripts/run_tests b/scripts/run_tests
--- a/scripts/run_tests
+++ b/scripts/run_tests
@@ -15,6 +15,12 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
+"${TOP_DIR}/scripts/run_rust_tests"
+if [ $? -ne 0 ]; then
+  echo "Rust tests failed."
+  exit 1
+fi
+
 "${TOP_DIR}/scripts/run_python_tests"
 if [ $? -ne 0 ]; then
   echo "Python tests failed."
