fix(scripts): do not allow running scripts as root; prevent accidental mishaps; update rust checks (#259)
CHANGELOG:
- [ ] Fix scripts so that the fail when run as root to prevent
  accidental mishaps.
- [ ] Update rust lint checks.
- [ ] Handlebarrz has linker errors when built individually, so exclude
  temporarily from workspace Cargo.toml.
- [ ] Move handlebarrz-specific script to scripts/run_handlebarrz_tests
- [ ] Add scripts to test rust code with nightly (non-failing) and stable.

diff --git a/scripts/run_tests b/scripts/run_tests
--- a/scripts/run_tests
+++ b/scripts/run_tests
@@ -17,6 +17,11 @@
 
 set -euo pipefail
 
+if ((EUID == 0)); then
+  echo "Please do not run as root"
+  exit 1
+fi
+
 TOP_DIR=$(git rev-parse --show-toplevel)
 
 "${TOP_DIR}/scripts/run_go_tests"
@@ -25,9 +30,15 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-"${TOP_DIR}/scripts/run_rust_tests"
+"${TOP_DIR}/scripts/run_rust_checks"
 if [ $? -ne 0 ]; then
   echo "Rust tests failed."
+  exit 1
+fi
+
+"${TOP_DIR}/scripts/run_handlebarrz_tests"
+if [ $? -ne 0 ]; then
+  echo "Handlebarrz tests failed."
   exit 1
 fi
 
