refactor: clean up spec.test.ts to prepare for translation to Go and Python; other minor fixes to test CI (#78)
CHANGELOG:
- [ ] Refactor test harness to prepare for translation to Go and Python.
- [ ] Update hooks to run all tests
- [ ] Configure CI and hooks to fail on failing tests since the team
  finds that comfortable and will translate bottom up.
- [ ] Clean up tests to reflect that.
- [ ] Fix some lint in dir.test.ts and adapters.ts
- [ ] Add some convenience scripts to the root package.json file.
- [ ] Update pnpm to 10.2.0 to stay at the same version as Genkit.
- [ ] Add a Role enum type for the role.
- [ ] Add docstrings to more types in typing.py
- [ ] Configure ruff to clean up unused imports and variables.

diff --git a/scripts/run_js_tests b/scripts/run_js_tests
--- a/scripts/run_js_tests
+++ b/scripts/run_js_tests
@@ -15,7 +15,7 @@ NODE_VERSIONS=(
   "23"
 )
 
-if [[ -z "${NVM_DIR:-}" ]]; then
+if [[ -z ${NVM_DIR-} ]]; then
   echo "NVM_DIR is not set. Please ensure nvm is installed and properly configured."
   exit 1
 fi
@@ -28,6 +28,10 @@ for VERSION in "${NODE_VERSIONS[@]}"; do
   nvm install "${VERSION}" || true
   nvm use "${VERSION}"
   cd "${TOP_DIR}/js" && pnpm install && pnpm run test
+  if [ $? -ne 0 ]; then
+    echo "JavaScript tests failed."
+    exit 1
+  fi
 done
 
 nvm use default
